### ISSUE TITLE
OnPauseEvent doesn't work

### ISSUE THREAD

**Issue by kirvigen** [KevinnZou/compose-multiplatform-lifecycle-tracker#1]
The OnPause Event does not arrive when exiting the application on iOS

compose = "1.6.1"
compose-plugin = "1.5.12"
ios = 17.0.3

**Comment by KevinnZou** [comment]
@kirvigen Thanks for your feedback! It should be fixed in version 0.0.2. Please let me know if you have any further questions!

**Comment by kirvigen** [comment]
> @kirvigen Thanks for your feedback! It should be fixed in version 0.0.2. Please let me know if you have any further questions!

Yes! Everything works, thank you!
