### ISSUE TITLE
return event in compose

### ISSUE THREAD

**Issue by nickfaces** [KevinnZou/compose-multiplatform-lifecycle-tracker#3]
Hi!

I look at sample, works fine. But how I can return event in compose fun or start another compose fun from "onEvent" ?

**Comment by KevinnZou** [comment]
This is a common issue that often arises in the reactive UI framework. The simplest approach is to define a State and depend on this state within a Composable function to control the UI. In this case, you only need to update the state within the onEvent, which will trigger the update of the UI.

You could refer to this [video](https://www.youtube.com/watch?v=rmv2ug-wW4U) for reference.
